// <auto-generated />
using ExamWeb_ThanhXuanPhuc.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExamWeb_ThanhXuanPhuc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250611010702_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExamWeb_ThanhXuanPhuc.Models.Phim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DienVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("GiaVe")
                        .HasColumnType("float");

                    b.Property<int>("ThoiLuong")
                        .HasColumnType("int");

                    b.Property<bool>("TrongNuoc")
                        .HasColumnType("bit");

                    b.Property<string>("TuaDe")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Phims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DienVien = "Lý Hải",
                            GiaVe = 75000.0,
                            ThoiLuong = 110,
                            TrongNuoc = true,
                            TuaDe = "Lật Mặt 6"
                        },
                        new
                        {
                            Id = 2,
                            DienVien = "Robert Downey Jr.",
                            GiaVe = 95000.0,
                            ThoiLuong = 181,
                            TrongNuoc = false,
                            TuaDe = "Avengers: Endgame"
                        },
                        new
                        {
                            Id = 3,
                            DienVien = "Leonardo DiCaprio",
                            GiaVe = 85000.0,
                            ThoiLuong = 148,
                            TrongNuoc = false,
                            TuaDe = "Inception"
                        },
                        new
                        {
                            Id = 4,
                            DienVien = "Trấn Thành",
                            GiaVe = 80000.0,
                            ThoiLuong = 128,
                            TrongNuoc = true,
                            TuaDe = "Bố Già"
                        },
                        new
                        {
                            Id = 5,
                            DienVien = "Joaquin Phoenix",
                            GiaVe = 90000.0,
                            ThoiLuong = 122,
                            TrongNuoc = false,
                            TuaDe = "Joker"
                        },
                        new
                        {
                            Id = 6,
                            DienVien = "Ngô Thanh Vân",
                            GiaVe = 78000.0,
                            ThoiLuong = 98,
                            TrongNuoc = true,
                            TuaDe = "Hai Phượng"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
